name: Java Spring Boot CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Use Java 17, which matches your project's version
          distribution: 'adopt'  # Use AdoptOpenJDK distribution
      - name: Set execute permissions for gradlew
        run: chmod +x gradlew

      - name: Build and Test
        run: ./gradlew build  # Use Gradle to build and run tests

      - name: Build Docker Image
        run: docker build -t email-service .  # Build Docker image based on Dockerfile

      - name: Log in to GitHub Container Registry
        env:
          CR_PAT: ${{ secrets.EMAIL_SERVICE_DEV }}
        run: |
            echo $CR_PAT | docker login ghcr.io -u EvaRusinova --password-stdin

      - name: Tag and Push Docker Image
        run: |
          docker tag email-service ghcr.io/eva_rusinova/email-service:latest
          docker push ghcr.io/eva_rusinova/email-service:latest
