name: Build and Tag Docker Image

on:
  push:
    branches:
      - dev

env:
  IMAGE_TAG: latest
  DOCKER_IMAGE_NAME: email-service

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Docker Image
        run: docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }} .