name: Java Spring Boot CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Use Java 17, which matches your project's version
          distribution: 'adopt'  # Use AdoptOpenJDK distribution
      - name: Set execute permissions for gradlew
        run: chmod +x gradlew

      - name: Build and Test
        run: ./gradlew build  # Use Gradle to build and run tests

      - name: Build Docker Image
        run: docker build -t email-service .  # Build Docker image based on Dockerfile

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.email-service-dev }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Tag and Push Docker Image
        run: |
            docker tag email-service ghcr.io/eva_rusinova/email-service:latest
            docker push ghcr.io/eva_rusinova/email-service:latest
  deploy:
    needs: build  # Wait for the "build" job to complete before starting this job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Start Docker Containers
        run: docker-compose up -d

      - name: Wait for Services to Start
        run: docker-compose logs -f  # Monitor logs to see if everything starts correctly

      # Note: We pass environment variables to the Docker container using the `env` option in docker-compose.yml
