name: Java Spring Boot CI/CD

on:
  push:
    branches:
      - dev

env:
  IMAGE_TAG: latest
  DOCKER_IMAGE_NAME: email-service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Set execute permissions for gradlew
        run: chmod +x gradlew

      - name: Build and Test
        run: ./gradlew build

      - name: Build Docker Image
        run: docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

#      - name: Log in to GitHub Container Registry
#        env:
#          CR_PAT: ${{ secrets.EMAIL_SERVICE_DEV }}
#        run: |
#          echo $CR_PAT | docker login ghcr.io -u EvaRusinova --password-stdin
#
#      - name: Tag and Push Docker Image
#        run: |
#          docker tag email-service ghcr.io/eva_rusinova/email-service:latest
#          docker push ghcr.io/eva_rusinova/email-service:latest
